### ISSUE TITLE
Python API Allocations, copying etc

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/SpaceVecAlg#18]
Are there any details/particulars of the python API I should be aware of that could differ from my typical expectations and lead to tricky bugs? For instance, when are objects copied vs modified in place?

**Comment by gergondet** [comment]
Hi Andrew,

I can't think of such issues with the Python API. Do you have something more specific in mind?

One thing to keep in mind is that the way Eigen3ToPython is written doesn't allow reference-based access, so the following (valid but unusual) program in C++:

```c++
auto pt = sva::PTransformd::Identity();
pt.translation().z() = 1.0;
// or
pt.translation() = Eigen::Vector3d::UnitZ();
```

Cannot be ported to Python directly:

```python
pt = sva.PTransformd.Identity()
pt.translation().z() = 1.0 # SyntaxError: can't assign to function call
pt.translation() = eigen.Vector3d.UnitZ() # SyntaxError: can't assign to function call
```

Importantly, `pt.translation()`, in the example above, is a copy of the PTransform translation component where the C++ API returns a reference to that object.

**Comment by ahundt** [comment]
One other thing I've forgotten a few times is:
```python
q = Eigen.Quaterniond().setIdentity()
# results in q being set to None
```

**Comment by gergondet** [comment]
Yes, because `setIdentity()` works in-place on the quaternion and returns a reference to the quaternion.

In C++ the following is wrong:

```cpp
auto q = Eigen::Quaterniond().setIdentity();
```

`auto` resolves to `Eigen::Quaterniond&` and q is a reference to a temporary variable (i.e. you're going to have a bad time).

On the other hand:
```cpp
Eigen::Quaterniond q = Eigen::Quaterniond().setIdentity();
```
is perfectly ok but it also has a very different meaning (copy/move assignment).
