### ISSUE TITLE
Does PPA include python bindings?

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/SpaceVecAlg#27]
Does the ppa installation include the python bindings?

**Comment by gergondet** [comment]
Yes.

The packages are:
- `python-spacevecalg` for Python 2
- `python3-spacevecalg` for Python 3

The same goes for other packages in the stack. Getting `python-tasks` should get you everything for Python 2 (resp. `python3-tasks` for Python 3)

**Comment by ahundt** [comment]
Cool! That might make my life much easier! So something like the following should work?

```
sudo add-apt-repository ppa:pierre-gergondet+ppa/multi-contact-unstable
sudo apt-get update
sudo apt-get install python-tasks python3-tasks
python2 -c 'import sva; import tasks'
python3 -c 'import sva; import tasks'
```

**Comment by gergondet** [comment]
Yes. Just tested on a fresh docker ubuntu:16.04 (+ `software-properties-common` for `add-apt-repository`) and it works :)

**Comment by ahundt** [comment]
Awesome!
