### ISSUE TITLE
Angular velocity conversion between left/right-handed coordinates

### ISSUE THREAD

**Issue by mmurooka** [jrl-umi3218/SpaceVecAlg#45]
SpaceVecAlg represents the variables in the left-handed coordinate. Therefore, the orientation represented by the right-handed coordinate needs to be inversed (i.e., transpose the rotation matrix) as follows:
https://github.com/jrl-umi3218/SpaceVecAlg/blob/676a64c47d650ba5de6a4b0ff4f2aaf7262ffafe/src/SpaceVecAlg/Conversions.h#L49
Are some similar transformations necessary for the other variables (**velocity,  acceleration, and force**), which are represented by the right-hand coordinate? Sorry for the simple question.

**Comment by gergondet** [comment]
Hi @mmurooka 

I think there was a bit of a confusion when we wrote the documentation about this and in fact we do not use a left-handed coordinate system. Rather, the rotation convention taken by Featherstone for Plucker transform between two frames A and B is different from the homogeneous transform convention and thus the transpose is necessary when converting between Plucker transform and homogeneous coordinates. However, in general we should not need to perform these conversions for velocity/acceleration/force quantities.
