### ISSUE TITLE
Affine3d and PTransformd.inverse() support

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/SpaceVecAlg#5]
I might create a pull request for initializing a PTransformd with an Affine3d, and adding .inverse() to PTransformd since that will make it consistent with its own functions and the equivalents in Eigen.

1. Is there interest, that is can I expect a reasonable implementation and pull request like this would be merged?

2. The Affine3d rotation component [is inverted per the SpaceVecAlg convention](https://github.com/jrl-umi3218/Tasks/issues/10#issuecomment-257793242). Should this be handled here, or perhaps in a separate conversion header?

**Comment by haudren** [comment]
You can submit a PR to initialize a PTransformd from an Affine3d, it is always good to have a better interoperability with Eigen.

For your second point, no it should not: the `inverse()` convention is a _RBDyn_ convention. Thus it should not be handled here (and it is of course strictly a no-go to modify the default behaviour).

**Comment by ahundt** [comment]
To verify, for item 1 I then assume it should not perform an inverse in the constructor. 

For item 2 would a conversion.h in RBDyn with documentation of why it exists be appropriate, and provides functions that perform the inversion for various appropriate types like Affine3d (though templated for the general versions), quaternion, matrixXd etc?  

I also understand that switching conventions there would be a big transition like the one from Eigen2 to Eigen3 so it most likely isn't practical or worthwhile to make changes everywhere across many libraries, which would be necessary for such a low level change!

**Comment by haudren** [comment]
This will be fixed (at last!) by #15 . Please have a look if you have any remarks / questions.
